export const HUMAN_GRADING_TEXT = {
  title: "Your scores and comments",
  optional: "Optional",
  comments: "Comments (optional)",
  savedComments: "Your comments",
  commentsHint: "Note problems in the work and suggestions for improvement. Saved for staff and included in CSV exports; not emailed to students.",
  commentsPlaceholder: "e.g. Explain the assumptions behind the model and check the units in the derivation.",
  save: "Save scores and comments",
  edit: "Edit scores and comments",
  saved: "Your scores and comments were saved",
  saveFailed: "Failed to save your scores and comments",
  cancel: "Cancel",
  total: "Total",
  totalOnly: "Total only",
  perItem: "Per item",
  scoringMode: "Scoring mode",
  item: "Item",
  you: "You",
  ai: "AI",
  difference: "Δ (you − AI)",
  totalHint: "Enter one overall score to compare with the AI's total. Scores can be changed later.",
  itemsHint: "Enter your own score per item to compare it with the AI's. Scores can be changed later.",
  scoreOutOfRange: (name: string, max: number) => `${name} must be a number between 0 and ${max}`,
  savedAt: (date: string) => `Saved ${date}`,
  savedBy: (name: string) => ` by ${name}`,
} as const;
