export const QUESTION_BANK_TEXT = {
  heading: "What to do",
  source: "View original document",
  choose: "Choose Question Bank problem",
  change: "Change linked problem",
  confirm: "Confirm problem",
  saving: "Saving…",
  cancel: "Cancel",
  search: "Search Question Bank",
  searchPlaceholder: "Search by title, keywords or problem ID…",
  suggested: "Suggested problems — confirm the correct one",
  browse: "All Question Bank problems",
  preview: "Preview — not saved yet",
  confirmed: "Confirmed problem",
  exact: "Exact title match · not yet confirmed",
  unmatched: "No confirmed problem. Choose the matching Question Bank problem to show its instructions.",
  unavailable: "The saved problem is unavailable in this catalog. Choose a replacement to show its instructions.",
  empty: "No close matches. Try fewer keywords, or clear the search to browse all problems.",
  description: "Compare the full title and instructions before confirming. Similar titles can describe different physics problems.",
  displayOnly: "Reference only. Linking a problem does not change the title, AI evaluation or scores.",
  formHelp: "Optional: link a Question Bank problem for its original instructions. This does not change the AI grading criteria.",
  saved: "Question Bank problem saved",
  saveError: "Could not save the problem. Your previous selection has not changed.",
} as const;
