-- AlterTable
ALTER TABLE "PresentationGradingJob" ADD COLUMN IF NOT EXISTS "humanComments" TEXT,
ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "ReportGradingJob" ADD COLUMN IF NOT EXISTS "humanComments" TEXT,
ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
